FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD springboot.jar /opt/springboot/
EXPOSE 8080
WORKDIR /opt/springboot/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "springboot.jar"]
