server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
    